### ISSUE TITLE
Can not unpack exe files

### ISSUE THREAD

**Issue by DevX-Cipher** [SteamAutoCracks/Steam-auto-crack#13]
hi im doing a test of this on dyling light 2 Unpack error. File not Packed or Packed by Other Packer/Protector.
All file Unpacked.

i also tried other games doesnt seem to work either

**Comment by cRu572Vltn** [comment]
That's because Dying Light 2 is protected by Denuvo, not Steam's typical DRM, duh. You'll never be able to crack it with Goldberg, you have to wait until some cracker or scene uploader decides to upload it to the Internet (EMPRESS, for example).

> i also tried other games doesnt seem to work either

Also protected by Denuvo? If so, you know the answer.
If it's an old game you sometimes need the corresponding game fix, an emulator is not always enough. (In this case, the S.T.A.L.K.E.R. games, for example).

**Comment by DevX-Cipher** [comment]
Yer make sensor so this just old stuff then

**Comment by oureveryday** [comment]
Denuvo game, this tool won't works.
