### ISSUE TITLE
I need some help since I am really confused

### ISSUE THREAD

**Issue by TheHugeFluff** [SteamAutoCracks/Steam-auto-crack#25]
Since there is no tutorial or help I am having issues cracking. Like do I crack a game or download crack games? I speak english so if you could provide help in that language thanks. but I do the steam app id: 250320

It says crack finished or something and I look in the file that I put it to and nothing is there. I am confused on how this works could you please help me. Thank you. If this works anymore.

**Comment by TheHugeFluff** [comment]
Is it like you bought a game and you make it cracked or what? I am really confused on the purpose of the application.

**Comment by ExLuck6** [comment]
> Is it like you bought a game and you make it cracked or what? I am really confused on the purpose of the application.

this is an automatic cracker + goldberg emulator applier for games that have Steam DRM (the stream protection that comes with all steam games), it won't be able to crack games that have extra protection (like games with Denuvo and a Virtual Machine Protection)

First thing you need is to get the clean steam files of the game you want. (get the clean steam files from websites like cs(dot)rin(dot)ru

Remove the (dot) obviously, and replace the (dot) with an actual dot. You need to create an account with that website (For free of course)

then inside that website, go to the "Steam content sharing" and search for the clean files of the game you want.

Second step, extract the clean steam files you downloaded anywhere in your computer

Third step, open this program as administrator (right click the .exe of the program and then click "run as administrator")

Fourth step, click "Auto Crack"

Fifth Step, in the "Game Path", click the three dots "..." and choose the game folder that has the .exe of the clean steam files you downloaded, you must choose the folder that has the .EXE of the game! so make sure you select the folder that HAS THE .EXE of the game!!

(perhaps sometimes in certain games, this won't 100% always be the case, but as a general rule, just make the path be the same folder as the .EXE of the game)

Sixth step, in the Steam App ID, you simply put the APP ID of the steam game you are trying to crack! in your case, its 250320

You can get the APP ID of any steam game from the website called "SteamDB" (just google NameOfTheGameYouHave SteamDB)


Seventh step, all the other options can be left as default, then click "Start Crack" and wait a bit till the program confirms that the crack has been succesfull.

That's it! The game has been cracked! You can now play it without having steam open, you can play it without confirming to steam that you own the game, you can play it on any computer even without steam installed!


OPTIONAL STEP -> only for games that are older than May 2016 you would need to generate the Steam Interfaces which is easily generated from within the Auto Crack window (but you have to generate it AFTER you have cracked it, so you just have to click "Auto Crack" again and then choose the steam_api.bak path (in the place that has the .exe of the game) then click "generate" , that's it.

**Comment by ExLuck6** [comment]
Explanation related to the Settings area in the "Auto Crack" window.

These settings are related to the Goldberg Emulator that gets auto applied after the crack.

Change Default Save Path: (this changes the default save path of games that use goldberg emulator, the default path is somewhere in %appdata% Local folder, this makes it so this specific game has a specific unique save folder in a place you want)

Use Steam API Key: (if you leave it empty/not ticked/default then it will generate a random number, but you can also use your own steam API key, google how to find out your steam account steam api key, in general, its use is to ensure that you are "unique" when playing the game for multiplayer/LAN purposes)

Generate Achievement Images tickbox (not 100% sure what it does but I guess its related to generating the achievement icons of steam?? So you can obtain the achievements?? ingame??, idk, i always got it ticked but I didn't really notice it taking any effect but it does generate a folder with the images... so i guess it does do it's job..

Language: (this is the language you would want the game to become) (default is english)

Listen Port: (this is the port that the emulator uses to connect players together through LAN, you can make this port whatever you want but generally leave it as default unless you know what you are doing, both players need to have the same listening port in their emulator settings in order to be able to play LAN together) (the default is 47584)

Account Name: (this is the name of your "fake" steam account, a general rule is to make it a unique name so that when you play LAN, you and the other person will both have different unique names) (the default is Goldberg)

Steam ID: (this is your "fake" steam ID, you can leave it default or make it 0 and it will auto generate a random ID, this ensures that your game profile is "unique" for multiplayer/LAN purposes, you can also literally use any ID or just straight up change it to your actual Steam account ID (google how to find that out, its very easy), also it acts as a unique identifier for your save files, so if you use a different ID than what you usually use, then you will find out that you can't access your old save file because it is tied to a different ID)

the "Force" checkbox basically makes the goldberg emulator forcefully use the settings you have set, this is because goldberg emulator can exist both in the %appdata% of your computer as well as in your game files itself.

So if you want to make specific games use specific settings instead of a "Global setting" that always gets used, you should tick the "Force" checkbox.

The tickbox of "Offline mode" ensures the game will start in Offline mode instead of attempting to connect to any online thing

the tickbox of "disable networking" is relating to disabling stuff like analytics and things like that that the game sends over the internet to their servers or whatever.

the tickbox of "disable overlay" is to disable the overlay of goldberg emulator/steam , the alt+tab thingy

Custom Broadcast IP: (not 100% sure what this is but my guess is that you use it to broadcast a custom ip of yours so that others can connect to that custom IP and play together with you)

**Comment by ExLuck6** [comment]
a nice trick if you want multiple save files for games that don't allow multiple save files/profiles is to force the account name and steam id and change the save path to somewhere local.

Then after that, when you want to change to a different save file, open the steam_settings folder in the game that you cracked and change the steam ID and account name to something else.

and of course, don't forget to save your old name and old steam id somewhere so you can re-use it to access your old save file.

**Comment by ExLuck6** [comment]
> Is it like you bought a game and you make it cracked or what? I am really confused on the purpose of the application.

also, this program is useful for when you want to play steam games that you already own but don't have steam installed/opened/logged in for whatever reason/new computer/no internet.

I use it sometimes to while backing-up steam games I already own. Mainly for archiving purposes, because randomly someday the game could get removed from steam for whatever reason (licensing etc etc).

**Comment by TheHugeFluff** [comment]
thank you

**Comment by oureveryday** [comment]
@ExLuck6 Thanks for your explanation!
https://github.com/oureveryday/Steam-auto-crack/wiki Here is full user manual.
